server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

api:
  gateway:
    url: http://localhost:8082

#  instance:
#    prefer-ip-address: true