server:
  port: 8081

spring:
  application:
    name: ACCOUNT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka


